### ISSUE TITLE
Awesome Calendar App for Android phone.

### ISSUE THREAD

**Issue by lovebdsobuj** [hidroh/calendar#1]
I used your calendar app today.
It's really nice work.

I'll be glad, if you tell me, 
> How to set calendar screen expandable always?

User can collapse calendar screen anytime.

**Comment by hidroh** [comment]
You can edit `MainActivity` layout and change default visibility of calendar to visible, plus set the default toolbar toggle state to checked state.

**Comment by lovebdsobuj** [comment]
Thank you so much.

Just one another help I need.

> How can I add some default (pre-built/built-in) **Event** information?

**Comment by hidroh** [comment]
It already uses calendar provider, so if you have another stock calendar app on your device you can manage events in both. By default the app will create a new local calendar if none exists on your device.

**Comment by lovebdsobuj** [comment]
Actually, I want to make Holiday Calendar 2016.
So, I want to add built-in holiday information.

Eg: 
01 01 2016 - New year.
08 02 2016 - Chinese Lunar New Year's Day

I want to insert this information as built-in.

**Comment by hidroh** [comment]
I would either store them as app resources (for those events that never change every year), or host that list of events somewhere, e.g. as github raw content with cache directives. On app startup you check if they have been synced before/is outdated, and do a background sync if needed.

**Comment by lovebdsobuj** [comment]
> I would either store them as app resources

also sync will be good.

1st, 
Store them as app resources, 
2nd,
User can check event list online.

It'll be pretty good I hope.

**Comment by lovebdsobuj** [comment]
And If you tell me choose one, then I choose second option.
> github raw content with cache directives. On app startup you check if they have been synced before/is outdated, and do a background sync if needed.

Aftre opening `My Calendar` app pop-up window show "Do you want add (this year) 2016 Holiday information to **My Calendar** app?" 

If yes, then sync will start, If no, user can wish sync it later from `menu`.

![my calendar holiday pop-up window](https://cloud.githubusercontent.com/assets/10352682/14559584/991ef276-032b-11e6-86d1-fd8aca04c112.png)

**Comment by lovebdsobuj** [comment]
Current date/Today's style,
Like this...
![my calendar - current date style](https://cloud.githubusercontent.com/assets/10352682/14560434/a382c9bc-0331-11e6-8418-c6dd0b2d1f9c.png)
Looking good, I think.

**Comment by lovebdsobuj** [comment]
and "Discard changes" window only show when user something write, edit (changes) and click back.
If event title empty, nothing writes, edited (changes) and click back then simply back to home screen without "Discard changes" ask.
![screenshot-2016-04-15-1752481](https://cloud.githubusercontent.com/assets/10352682/14560953/db1b5e40-0334-11e6-94fb-1bffa4c574f6.png)

**Comment by lovebdsobuj** [comment]
Brother, I just can get help integrating holiday information, holiday information will stored in raw file on github?
I try to contact with you via phone call. But can't...

**Comment by hidroh** [comment]
I suggest you bring your problem to other places like Stackoverflow or Reddit for help. And please do not contact me personally outside Github.
