### ISSUE TITLE
I had little bit budget to implement Holiday Info sync feature

### ISSUE THREAD

**Issue by lovebdsobuj** [hidroh/calendar#3]
I had little bit budget to implement Holiday Info sync feature by you.

I need this feature.
![screenshot_06_2016 05 02](https://cloud.githubusercontent.com/assets/10352682/14947543/25269dfe-1057-11e6-80c8-0191a484c9ca.png)
What about you, sir?

**Comment by hidroh** [comment]
Please feel free to fork the project to work on your own features. I don't have plan to include it in this project.

**Comment by lovebdsobuj** [comment]
I will fork this project and change package name, icons etc.
But I can't able to add that holiday information sync features.
I need your help. 
Think me as your little brother, who don't know much more about programming. 

I want to publish this app on Google Play Store. 
I kept this app developer to you. 
It may help you to increase your publicity.

and I want to pay you 20-30$ as your onetime coffee bill.

Please, do it for me, when you have a little bit free time.

**Comment by hidroh** [comment]
Hi I don't do freelance. This is an open source project, you can get the code then hire some other freelancer to continue with features you want.
